version: '3.4'

services:
  loggingdb:
    container_name: loggingdb
    environment:
      - MONGO_INITDB_DATABASE=loggingdb
      - MONGO_INITDB_ROOT_USERNAME=ilgcns
      - MONGO_INITDB_ROOT_PASSWORD=iLGCNS24!
    restart: always
    ports:
      - 27017:27017

  ilgdb:
    container_name: ilgdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=iLGCNS24!
    restart: always
    ports:
      - "1433:1433"

  ilg.api:
    env_file:
      - .env.Development
    ports:
      - "6080:8080"
      - "6081:8081"
    depends_on:
      - loggingdb
      - ilgdb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro