version: '3.4'

services:
  loggingdb:
    image: mongo

  ilgdb:
    image: mcr.microsoft.com/mssql/server

  ilg.api:
    image: ${DOCKER_REGISTRY-}ilgapi
    build:
      context: .
      dockerfile: ./../iLG.API/Dockerfile
volumes:
  ilgdb_data: