version: '3.4'

services:
  loggingdb:
    image: mongo

  ilgdb:
    image: mcr.microsoft.com/mssql/server
 
  ilgcache:
    image: redis

  ilg.api:
    image: ${DOCKER_REGISTRY-}ilgapi
    build:
      context: .
      dockerfile: ./../iLG.API/Dockerfile