version: '3.4'

services:
  loggingdb:
    container_name: loggingdb
    env_file:
     - ./environment/loggingdb/.env.Development
    restart: always
    ports:
      - 27017:27017

  ilgdb:
    container_name: ilgdb
    env_file:
      - ./environment/ilgdb/.env.Development
    restart: always
    ports:
      - "1433:1433"

  ilg.api:
    env_file:
      - ./environment/ilgapi/.env.Development
    ports:
      - "6080:8080"
      - "6081:8081"
    depends_on:
      - loggingdb
      - ilgdb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro